#AreaManager
SELECT * FROM AreaManager;
INSERT INTO AreaManager VALUES('E331', "Plano");

# Make Contract
SELECT * FROM MakeContract;
INSERT INTO  VALUES('E111');
INSERT INTO  VALUES('E237');
INSERT INTO  VALUES('E983');
INSERT INTO  VALUES('E764');
INSERT INTO  VALUES('E123');
INSERT INTO  VALUES('E468');
INSERT INTO  VALUES('E083');
INSERT INTO  VALUES('E763');
INSERT INTO  VALUES('E394');
INSERT INTO  VALUES('E094');
INSERT INTO  VALUES('E875');
INSERT INTO  VALUES('E346');
INSERT INTO  VALUES('E986');
INSERT INTO  VALUES('E999');



# Restaurants

# Restaurant Type



SELECT * FROM Orders;
INSERT INTO Orders VALUES(248194927, "S2", "E173", "EJW5342", 3, "Good!")

# Orders

# Payment

