
SELECT * FROM Customer;
INSERT INTO  VALUES();

SELECT * FROM DeliveryAddress;
INSERT INTO  VALUES();

SELECT * FROM PremiumMember;
INSERT INTO  VALUES();

SELECT * FROM Employee;
INSERT INTO  VALUES();

SELECT * FROM PhoneNumber;
INSERT INTO  VALUES();

SELECT * FROM OrdinaryCustomer;
INSERT INTO  VALUES();

SELECT * FROM SilverMember;
INSERT INTO  VALUES();

SELECT * FROM Staff;
INSERT INTO  VALUES();

SELECT * FROM AreaManager;
INSERT INTO  VALUES();

SELECT * FROM Deliverer;
INSERT INTO  VALUES();

SELECT * FROM MemberCard;
INSERT INTO  VALUES();

SELECT * FROM Vehicle;
INSERT INTO  VALUES();

SELECT * FROM MealPass;
INSERT INTO  VALUES();

SELECT * FROM Shop;
INSERT INTO  VALUES();

SELECT * FROM OpeningTime;
INSERT INTO  VALUES();

SELECT * FROM ClosingTime;
INSERT INTO  VALUES();

SELECT * FROM MakeContract;
INSERT INTO  VALUES();

SELECT * FROM Promotion;
INSERT INTO  VALUES();

SELECT * FROM Comment;
INSERT INTO  VALUES();

SELECT * FROM Restaurant;
INSERT INTO  VALUES();

SELECT * FROM RestaurantType;
INSERT INTO  VALUES();

SELECT * FROM Supermarket;
INSERT INTO  VALUES();

SELECT * FROM Product;
INSERT INTO  VALUES();

SELECT * FROM Sell;
INSERT INTO  VALUES();

SELECT * FROM Orders;
INSERT INTO  VALUES();

SELECT * FROM Payment;
INSERT INTO  VALUES();